(globalThis.sprites ??= {}).signpost = {
  legend: {
    k: 'Ink',
    h: 'E2',
    s: 'E0',
    a: 'E1',
  },
  frames: {
    signpost: [
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '......kkkkkkkkkkkkkkkkkkkk......',
      '.....khhhhhhhhhhhhhhhhhhhsk.....',
      '.....khaaaaaaaaaaaaaaaaaask.....',
      '.....khaaaaaaaaaaaaaaaaaask.....',
      '.....khaassssssssssssssaask.....',
      '.....khaassssssssssssssaask.....',
      '.....khaaaaaaaaaaaaaaaaaask.....',
      '.....khaasssssssssaaaaaaask.....',
      '.....khaasssssssssaaaaaaask.....',
      '.....khaaaaaaaaaaaaaaaaaask.....',
      '.....khaaaaaaaaaaaaaaaaaask.....',
      '.....kssssssssssssssssssssk.....',
      '......kkkkkkkkkkkkkkkkkkkk......',
      '.............khaask.............',
      '.............khaask.............',
      '.............khaask.............',
      '.............khaask.............',
      '.............khaask.............',
      '.............khaask.............',
      '.............khaask.............',
      '.............kkkkkk.............',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
    ],
  },
  faded: {},
  animations: {},
};
