(globalThis.sprites ??= {}).path = {
  legend: {
    p: 'E3',
    P: 'E4',
    e: 'E2',
  },
  frames: {
    'variant-0': [
      'pppppppppppppppppppppppppppppppp',
      'pppppppppppppppppppppppppppppppp',
      'pppppppppppppppppppppppppppppPPp',
      'pppppppppppppppppppppppppppppeep',
      'pppppppppppppppppppppppppppppppp',
      'pppppppppppppppppppppppppppppppp',
      'pppppppPPppppppppppppppppppppppp',
      'pppppppeeppppppPPppppppppppppppp',
      'ppppppppppppppppPppppppppppppppp',
      'pppppppppppppppppppppppppppppppp',
      'pppppppppppppppppppppppppppppppp',
      'pppppppppppppppppppppppppppppppp',
      'pppppppppppppppppppppppppppppppp',
      'pppppppppppppppppppppppppppppppp',
      'pppppppppPPppppppppppppppppppppp',
      'pppppppppPpepppppppppppppppppppp',
      'ppppppppppeepppppppppppppppppppp',
      'pppppppppppppppppppppppppppppppp',
      'pppppppppppppppppppppppppppppppp',
      'pppPPppppppppppppppppppppppppppp',
      'pppPpepppppppppppppppppppppppppp',
      'ppppeepppppppppppppppppppppppppp',
      'ppppppppppppppPPpppppppppppppppp',
      'ppppppppppppppeeppppeepppppppppp',
      'ppppppppppPPpppppppppeeepppppppp',
      'pppppeeppppPpPPppppppppppppppppp',
      'ppppppeeeppppPpepppppppppppppppp',
      'ppppppppppppppeepppppppppppppppp',
      'pppppppppppppppppppppppppppppppp',
      'pppppppppppppppppppppppppppppppp',
      'pppppppppppppppppppppppppppppppp',
      'pppppppppppppppppppppppppppppppp',
    ],
    'variant-1': [
      'pppppppppppppppppppppppppppppppp',
      'ppppppppppppppPPpppppppppppppppp',
      'ppppppppppppppeepppppppppppppppp',
      'pppppppppppppppppppppppppppppppp',
      'pppppppppppppppppppppppppppppppp',
      'pppppppppppppppppppppppppppppppp',
      'ppppppPPpppppppppppppppppppppppp',
      'ppppppPpeppppppppppppppppppppppp',
      'pppppppeeppppppppppeeppppppppppp',
      'ppppppppppppppppppppeeeppppppppp',
      'pppppppppppppppppppppppppppppppp',
      'pppppppppppppppppppppppppppppppp',
      'pppppppppppppppppppppppppppppppp',
      'pppppppppppppppppppppppppppppppp',
      'pppppppppppppppppppppppppppppppp',
      'pppppppppppppppppppppppppppppppp',
      'pppppppppppppppppppPPppppppppppp',
      'pppppppppppppppppppPpepppppppppp',
      'ppppppppppppppppppppeepppppppppp',
      'ppppppppppppppPPpppppppppppppppp',
      'pppppppppppppppPpppppppppppppppp',
      'ppppppppppppppppppppppppeepppppp',
      'pppppPPppppppppppppppppppeeepppp',
      'pppppeeppppppppppppppppppppppppp',
      'pppppppppppPPppPPppppppppppppppp',
      'pppppppppppeeppPpepppppppppppppp',
      'ppppppppppppppppeepppppppppppppp',
      'pppppppppppppppppppppppppppppppp',
      'ppppppppppppppppppppPPpppppppppp',
      'pppppppppppppppppppppPpppppppppp',
      'pppppppppppppppppppppppppppppppp',
      'pppppppppppppppppppppppppppppppp',
    ],
    'variant-2': [
      'pppppppppppppppppppppppppppppppp',
      'pppppppppppppppppppppppppppppppp',
      'pppppPPppppppppppppppppppppppppp',
      'pppppPpepppppppppppppppppppppppp',
      'ppppppeepppppPPppeeppppppppppppp',
      'pppppppppppppPpeppeeeppppppppppp',
      'ppppppppppppppeepppppppppppppppp',
      'pppppppppppppppppppppppppppppppp',
      'pppppppppppppppppppppppppppppppp',
      'pppppppppppppppppppppppppppppppp',
      'pppppppppppppppppppppppppppppppp',
      'pppppppppppppppppppppppppppppppp',
      'pppppppppppppppppppppppppppppppp',
      'pppppppppppppppppppppppppppppppp',
      'pppppppppppppppppppppppppppppppp',
      'pppppppppppppppppppppppppppppppp',
      'pppppppppppppppppppppppppppppppp',
      'pppppppppppppppppppppppppppppppp',
      'pppppppppppppppppppppppppppppppp',
      'pppppppppppppppppppppppppppppppp',
      'pppppppppppppppppppppppppppppppp',
      'ppppppPPpppppppppppppppppppppppp',
      'ppppppeepppppppppppppppppppppppp',
      'pppppppppppppppppppppppppppppppp',
      'pppppppppppppppppPPppppppppppppp',
      'pppppppppppppppppeeppppppppppppp',
      'ppppppppPPpppppppppppppppppppppp',
      'pppppppppPpppppppppppppppppPPppp',
      'pppppppppppppppppppPPppppppPpepp',
      'pppppppppppppPPppppeepeeppppeepp',
      'ppppppppppppppPppppppppeeepppppp',
      'pppppppppppppppppppppppppppppppp',
    ],
  },
  faded: {},
  animations: {},
};
