(globalThis.sprites ??= {}).orb = {
  legend: {
    k: 'Ink',
    a: 'R2',
    c: 'R3',
    b: 'R1',
    d: 'W2',
    e: 'W3',
    f: 'W1',
    g: 'V2',
    h: 'V3',
    i: 'V1',
    j: 'T2',
    l: 'T3',
    m: 'T1',
  },
  frames: {
    red: [
      '........................',
      '........................',
      '........................',
      '........................',
      '.........kkkkkk.........',
      '.......kkaaaaaakk.......',
      '......kcccaaaaaaak......',
      '.....kccaaaaaaaaabk.....',
      '.....kcaaaaaaaaaabk.....',
      '....kaaaaaaaaaaaabbk....',
      '....kaaaaaacaaaaabbk....',
      '....kaaaaacccaaabbbk....',
      '....kaaaacccccaabbbk....',
      '....kaaacccccccbbbbk....',
      '....kaaaabbbbbbbbabk....',
      '.....kaaaaaabbbbabk.....',
      '.....kbbbbbbbbbabbk.....',
      '......kbbbbbbbbbbk......',
      '.......kkbbbbbbkk.......',
      '.........kkkkkk.........',
      '........................',
      '........................',
      '........................',
      '........................',
    ],
    blue: [
      '........................',
      '........................',
      '........................',
      '........................',
      '.........kkkkkk.........',
      '.......kkddddddkk.......',
      '......keeedddddddk......',
      '.....keedddddddddfk.....',
      '.....keddddddddddfk.....',
      '....kddddddeeddddffk....',
      '....kddddddeefdddffk....',
      '....kddddeeeeeedfffk....',
      '....kddddeeeeeeffffk....',
      '....kdddddfeeffffffk....',
      '....kddddddeeffffdfk....',
      '.....kddddddffffdfk.....',
      '.....kfffffffffdffk.....',
      '......kffffffffffk......',
      '.......kkffffffkk.......',
      '.........kkkkkk.........',
      '........................',
      '........................',
      '........................',
      '........................',
    ],
    violet: [
      '........................',
      '........................',
      '........................',
      '........................',
      '.........kkkkkk.........',
      '.......kkggggggkk.......',
      '......khhhgggggggk......',
      '.....khhgggggggggik.....',
      '.....khggggggggggik.....',
      '....kgggggghhggggiik....',
      '....kggggghhhhgggiik....',
      '....kgggghhhhhhgiiik....',
      '....kgggghhhhhhiiiik....',
      '....kggggghhhhiiiiik....',
      '....kgggggghhiiiigik....',
      '.....kggggggiiiigik.....',
      '.....kiiiiiiiiigiik.....',
      '......kiiiiiiiiiik......',
      '.......kkiiiiiikk.......',
      '.........kkkkkk.........',
      '........................',
      '........................',
      '........................',
      '........................',
    ],
    teal: [
      '........................',
      '........................',
      '........................',
      '........................',
      '.........kkkkkk.........',
      '.......kkjjjjjjkk.......',
      '......kllljjjjjjjk......',
      '.....klljjjjjjjjjmk.....',
      '.....kljjjjjjjjjjmk.....',
      '....kjjjjlllllljjmmk....',
      '....kjjjjllllllmjmmk....',
      '....kjjjjllmmllmmmmk....',
      '....kjjjjllmjllmmmmk....',
      '....kjjjjllllllmmmmk....',
      '....kjjjjllllllmmjmk....',
      '.....kjjjjmmmmmmjmk.....',
      '.....kmmmmmmmmmjmmk.....',
      '......kmmmmmmmmmmk......',
      '.......kkmmmmmmkk.......',
      '.........kkkkkk.........',
      '........................',
      '........................',
      '........................',
      '........................',
    ],
  },
  faded: {},
  animations: {},
};
