import { PixelGrid, type Art, type HeroArt, type HeroDirectionArt, type Legend } from './art';

type Grid = readonly string[];
type Facing = keyof HeroArt;
type Frames = {
  readonly idle: Grid; readonly idleInhale: Grid; readonly idleSettle: Grid;
  readonly idleBlink?: Grid; readonly idleInhaleBlink?: Grid;
  readonly walkContactA: Grid; readonly walkPassing: Grid; readonly walkContactB: Grid;
};

const heroColors = {
  k: 'Ink', h: 'E3', H: 'E2', l: 'E4', e: 'E1', c: 'Paper', s: 'S2', S: 'S1', t: 'S3',
  p: 'P2', P: 'P1', q: 'P3', j: 'W1', J: 'W0', b: 'E1',
} as const satisfies Legend;
const stoneColors = { k: 'Ink', a: 'N3', b: 'N2', c: 'N4' } as const satisfies Legend;

const heroFrames: Record<Facing, Frames> = {
  down: {
    idle: [
      '................................',
      '.............kkkkkk.............',
      '...........kkhhhhhhkk...........',
      '.........kklllllhhhhhkk.........',
      '........khlllhhhhhhhhHHk........',
      '.......khllhhhhhhhhhhhHHk.......',
      '......khllhhhhhhhhhhhhhHHk......',
      '......khhhhhHhhhhhhHhhhHHk......',
      '.....khHhhHHHhhhhhhHHHhhHHk.....',
      '.....khHHHsssHHHHHHsssHHHHk.....',
      '.....khHsscesssssssscesSHHk.....',
      '...kkkhHsseesssssssseesSHHkkk...',
      '..klhHhHtteesssssssseesSHHHhhk..',
      '.kllhhHkkttsssssssssssSkkHhhhHk.',
      '.khhhHk..ksssssSSssssSk..khhHHk.',
      '.khHHk....kSssssssSSSk....khHHk.',
      '..kHHk...kkqSSSSSSSSpkk...kHHk..',
      '...kk..kkqqqpppppppppppkk..kk...',
      '......kpqqppppppppppppppPk......',
      '......kpppppppppppppppppPk......',
      '......kPPPppppppppppppPPPk......',
      '.......ksSPppppppppppPsSk.......',
      '.......ksSPppppppppppPsSk.......',
      '.......ksspPppppppppPpssk.......',
      '.......kSSJJJJJJJJJJJJSSk.......',
      '........kkjjjjjjjjjjjJkk........',
      '.........kjjjjjjjjjjjJk.........',
      '.........kjjjjjJJjjjjJk.........',
      '.........kjjjjjkkjjjjJk.........',
      '........keeeeek..keeeeek........',
      '........keeeeek..keeeeek........',
      '.........kkkkk....kkkkk.........',
    ],
    idleBlink: [
      '................................',
      '.............kkkkkk.............',
      '...........kkhhhhhhkk...........',
      '.........kklllllhhhhhkk.........',
      '........khlllhhhhhhhhHHk........',
      '.......khllhhhhhhhhhhhHHk.......',
      '......khllhhhhhhhhhhhhhHHk......',
      '......khhhhhHhhhhhhHhhhHHk......',
      '.....khHhhHHHhhhhhhHHHhhHHk.....',
      '.....khHHHsssHHHHHHsssHHHHk.....',
      '.....khHsssssssssssssssSHHk.....',
      '...kkkhHsssssssssssssssSHHkkk...',
      '..klhHhHtteesssssssseesSHHHhhk..',
      '.kllhhHkkttsssssssssssSkkHhhhHk.',
      '.khhhHk..ksssssSSssssSk..khhHHk.',
      '.khHHk....kSssssssSSSk....khHHk.',
      '..kHHk...kkqSSSSSSSSpkk...kHHk..',
      '...kk..kkqqqpppppppppppkk..kk...',
      '......kpqqppppppppppppppPk......',
      '......kpppppppppppppppppPk......',
      '......kPPPppppppppppppPPPk......',
      '.......ksSPppppppppppPsSk.......',
      '.......ksSPppppppppppPsSk.......',
      '.......ksspPppppppppPpssk.......',
      '.......kSSJJJJJJJJJJJJSSk.......',
      '........kkjjjjjjjjjjjJkk........',
      '.........kjjjjjjjjjjjJk.........',
      '.........kjjjjjJJjjjjJk.........',
      '.........kjjjjjkkjjjjJk.........',
      '........keeeeek..keeeeek........',
      '........keeeeek..keeeeek........',
      '.........kkkkk....kkkkk.........',
    ],
    idleInhale: [
      '................................',
      '.............kkkkkk.............',
      '...........kkhhhhhhkk...........',
      '.........kklllllhhhhhkk.........',
      '........khlllhhhhhhhhHHk........',
      '.......khllhhhhhhhhhhhHHk.......',
      '......khllhhhhhhhhhhhhhHHk......',
      '......khhhhhHhhhhhhHhhhHHk......',
      '.....khHhhHHHhhhhhhHHHhhHHk.....',
      '.....khHHHsssHHHHHHsssHHHHk.....',
      '.....khHsscesssssssscesSHHk.....',
      '...kkkhHsseesssssssseesSHHkkk...',
      '..klhHhHtteesssssssseesSHHHhhk..',
      '.kllhhHkkttsssssssssssSkkHhhhHk.',
      '.khhhHk..ksssssSSssssSk..khhHHk.',
      '.khHHk....kSssssssSSSk....khHHk.',
      '..kHHk..kkkqSSSSSSSSpkkk..kHHk..',
      '...kk..kqqqqppppppppppppk..kk...',
      '......kpqqppppppppppppppPk......',
      '......kpppppppppppppppppPk......',
      '......kPPPppppppppppppPPPk......',
      '.......ksSPppppppppppPsSk.......',
      '.......ksSPppppppppppPsSk.......',
      '.......ksspPppppppppPpssk.......',
      '.......kSSJJJJJJJJJJJJSSk.......',
      '........kkjjjjjjjjjjjJkk........',
      '.........kjjjjjjjjjjjJk.........',
      '.........kjjjjjJJjjjjJk.........',
      '.........kjjjjjkkjjjjJk.........',
      '........keeeeek..keeeeek........',
      '........keeeeek..keeeeek........',
      '.........kkkkk....kkkkk.........',
    ],
    idleInhaleBlink: [
      '................................',
      '.............kkkkkk.............',
      '...........kkhhhhhhkk...........',
      '.........kklllllhhhhhkk.........',
      '........khlllhhhhhhhhHHk........',
      '.......khllhhhhhhhhhhhHHk.......',
      '......khllhhhhhhhhhhhhhHHk......',
      '......khhhhhHhhhhhhHhhhHHk......',
      '.....khHhhHHHhhhhhhHHHhhHHk.....',
      '.....khHHHsssHHHHHHsssHHHHk.....',
      '.....khHsssssssssssssssSHHk.....',
      '...kkkhHsssssssssssssssSHHkkk...',
      '..klhHhHtteesssssssseesSHHHhhk..',
      '.kllhhHkkttsssssssssssSkkHhhhHk.',
      '.khhhHk..ksssssSSssssSk..khhHHk.',
      '.khHHk....kSssssssSSSk....khHHk.',
      '..kHHk..kkkqSSSSSSSSpkkk..kHHk..',
      '...kk..kqqqqppppppppppppk..kk...',
      '......kpqqppppppppppppppPk......',
      '......kpppppppppppppppppPk......',
      '......kPPPppppppppppppPPPk......',
      '.......ksSPppppppppppPsSk.......',
      '.......ksSPppppppppppPsSk.......',
      '.......ksspPppppppppPpssk.......',
      '.......kSSJJJJJJJJJJJJSSk.......',
      '........kkjjjjjjjjjjjJkk........',
      '.........kjjjjjjjjjjjJk.........',
      '.........kjjjjjJJjjjjJk.........',
      '.........kjjjjjkkjjjjJk.........',
      '........keeeeek..keeeeek........',
      '........keeeeek..keeeeek........',
      '.........kkkkk....kkkkk.........',
    ],
    idleSettle: [
      '................................',
      '.............kkkkkk.............',
      '...........kkhhhhhhkk...........',
      '.........kklllllhhhhhkk.........',
      '........khlllhhhhhhhhHHk........',
      '.......khllhhhhhhhhhhhHHk.......',
      '......khllhhhhhhhhhhhhhHHk......',
      '......khhhhhHhhhhhhHhhhHHk......',
      '.....khHhhHHHhhhhhhHHHhhHHk.....',
      '.....khHHHsssHHHHHHsssHHHHk.....',
      '.....khHsscesssssssscesSHHk.....',
      '.....khHsseesssssssseesSHHk.....',
      '...kkHhHtteesssssssseesSHHkkk...',
      '..klhHHkkttsssssssssssSkkkHhhk..',
      '.kllhhk..ksssssSSssssSk..khhhHk.',
      '.khhhHk...kSssssssSSSk...khhHHk.',
      '.khHHk...kkqSSSSSSSSpkk...khHHk.',
      '..kHHk.kkqqqpppppppppppkk.kHHk..',
      '...kk.kpqqppppppppppppppPk.kk...',
      '......kpppppppppppppppppPk......',
      '......kPPPppppppppppppPPPk......',
      '.......ksSPppppppppppPsSk.......',
      '.......ksSPppppppppppPsSk.......',
      '.......ksspPppppppppPpssk.......',
      '.......kSSJJJJJJJJJJJJSSk.......',
      '........kkjjjjjjjjjjjJkk........',
      '.........kjjjjjjjjjjjJk.........',
      '.........kjjjjjJJjjjjJk.........',
      '.........kjjjjjkkjjjjJk.........',
      '........keeeeek..keeeeek........',
      '........keeeeek..keeeeek........',
      '.........kkkkk....kkkkk.........',
    ],
    walkContactA: [
      '................................',
      '.............kkkkkk.............',
      '...........kkhhhhhhkk...........',
      '.........kklllllhhhhhkk.........',
      '........khlllhhhhhhhhHHk........',
      '.......khllhhhhhhhhhhhHHk.......',
      '......khllhhhhhhhhhhhhhHHk......',
      '......khhhhhHhhhhhhHhhhHHk......',
      '.....khHhhHHHhhhhhhHHHhhHHk.....',
      '.....khHHHsssHHHHHHsssHHHHk.....',
      '.....khHsscesssssssscesSHHk.....',
      '.....khHsseesssssssseesSHHk.....',
      '...kkHhHtteesssssssseesSHHkkk...',
      '..klhHHkkttsssssssssssSkkkHhhk..',
      '.kllhhk..ksssssSSssssSk..khhhHk.',
      '.khhhHk...kSssssssSSSk...khhHHk.',
      '.khHHk...kkqSSSSSSSSpkk...khHHk.',
      '..kHHk.kkqqqpppppppppppkk.kHHk..',
      '...kk.kpqqppppppppppppppPk.kk...',
      '......kpppppppppppppppppPk......',
      '......kPPPppppppppppppPPPk......',
      '.......kssPppppppppppPsSk.......',
      '.......kssPppppppppppPsSk.......',
      '.......kSSpPppppppppPpsSk.......',
      '........kkJJJJJJJJJJJJssk.......',
      '.........kjjjjjjjjjjjJSSk.......',
      '.........kjjjjjjjjjjjJkk........',
      '.........kjjjjjJJjjjjJk.........',
      '.........kjjjjjkkkeeeeek........',
      '........keeeeek..keeeeek........',
      '........keeeeek...kkkkk.........',
      '.........kkkkk..................',
    ],
    walkPassing: [
      '................................',
      '................................',
      '.............kkkkkk.............',
      '...........kkhhhhhhkk...........',
      '.........kklllllhhhhhkk.........',
      '........khlllhhhhhhhhHHk........',
      '.......khllhhhhhhhhhhhHHk.......',
      '......khllhhhhhhhhhhhhhHHk......',
      '......khhhhhHhhhhhhHhhhHHk......',
      '.....khHhhHHHhhhhhhHHHhhHHk.....',
      '.....khHHHsssHHHHHHsssHHHHk.....',
      '...kkkhHsscesssssssscesSHHkkk...',
      '..klhHhHsseesssssssseesSHHHhhk..',
      '.kllhHhHtteesssssssseesSHHHhhHk.',
      '.khhhHkkkttsssssssssssSkkkhhHHk.',
      '.khHHk...ksssssSSssssSk...khHHk.',
      '..kHHk....kSssssssSSSk....kHHk..',
      '...kk....kkqSSSSSSSSpkk....kk...',
      '.......kkqqqpppppppppppkk.......',
      '......kpqqppppppppppppppPk......',
      '......kpppppppppppppppppPk......',
      '......kPPPppppppppppppPPPk......',
      '.......ksSPppppppppppPsSk.......',
      '.......ksSPppppppppppPsSk.......',
      '.......ksspPppppppppPpssk.......',
      '.......kSSJJJJJJJJJJJJSSk.......',
      '........kkjjjjjjjjjjjJkk........',
      '.........kjjjjjJJjjjjJk.........',
      '.........kjjjjjkkjjjjJk.........',
      '........keeeeek..keeeeek........',
      '........keeeeek..keeeeek........',
      '.........kkkkk....kkkkk.........',
    ],
    walkContactB: [
      '................................',
      '.............kkkkkk.............',
      '...........kkhhhhhhkk...........',
      '.........kklllllhhhhhkk.........',
      '........khlllhhhhhhhhHHk........',
      '.......khllhhhhhhhhhhhHHk.......',
      '......khllhhhhhhhhhhhhhHHk......',
      '......khhhhhHhhhhhhHhhhHHk......',
      '.....khHhhHHHhhhhhhHHHhhHHk.....',
      '.....khHHHsssHHHHHHsssHHHHk.....',
      '.....khHsscesssssssscesSHHk.....',
      '.....khHsseesssssssseesSHHk.....',
      '...kkHhHtteesssssssseesSHHkkk...',
      '..klhHHkkttsssssssssssSkkkHhhk..',
      '.kllhhk..ksssssSSssssSk..khhhHk.',
      '.khhhHk...kSssssssSSSk...khhHHk.',
      '.khHHk...kkqSSSSSSSSpkk...khHHk.',
      '..kHHk.kkqqqpppppppppppkk.kHHk..',
      '...kk.kpqqppppppppppppppPk.kk...',
      '......kpppppppppppppppppPk......',
      '......kPPPppppppppppppPPPk......',
      '.......ksSPppppppppppPssk.......',
      '.......ksSPppppppppppPssk.......',
      '.......ksSpPppppppppPpSSk.......',
      '.......kssJJJJJJJJJJJJkk........',
      '.......kSSjjjjjjjjjjjJk.........',
      '........kkjjjjjjjjjjjJk.........',
      '.........kjjjjjJJjjjjJk.........',
      '........keeeeekkkjjjjJk.........',
      '........keeeeek..keeeeek........',
      '.........kkkkk...keeeeek........',
      '..................kkkkk.........',
    ],
  },
  up: {
    idle: [
      '................................',
      '.............kkkkkk.............',
      '...........kkhhhhhhkk...........',
      '.........kklllllhhhhhkk.........',
      '........khlllhhhHhhhhHHk........',
      '.......khllhhhhhHhhhhhHHk.......',
      '......khllhhhhhhHhhhhhhHHk......',
      '......khhhhhhhhhHhhhhhhHHk......',
      '.....khhhhhhhHhhHhhHhhhhHHk.....',
      '.....khhhhhhHhhhHhhhHhHHHHk.....',
      '.....khhhhhHhhhhHhhhhHHHHHk.....',
      '...kkkhhhhHhhhhhHhhhhhHHHHkkk...',
      '..klhHhhhHhhhhhhHhhhhhHHHHHhhk..',
      '.kllhhHkkhhhhhhhHhhHHHHkkHhhhHk.',
      '.khhhHk..khHHHHHHHHHHHk..khhHHk.',
      '.khHHk....kSssssssSSSk....khHHk.',
      '..kHHk...kkqSSSSSSSSpkk...kHHk..',
      '...kk..kkqqqpppppppppppkk..kk...',
      '......kpqqppppppppppppppPk......',
      '......kpppppppppppppppppPk......',
      '......kPPPppppppppppppPPPk......',
      '.......ksSPppppppppppPsSk.......',
      '.......ksSPppppppppppPsSk.......',
      '.......ksspPppppppppPpssk.......',
      '.......kSSJJJJJJJJJJJJSSk.......',
      '........kkjjjjjjjjjjjJkk........',
      '.........kjJJjjjjjJJjJk.........',
      '.........kjjjjjJJjjjjJk.........',
      '.........kjjjjjkkjjjjJk.........',
      '........keeeeek..keeeeek........',
      '........keeeeek..keeeeek........',
      '.........kkkkk....kkkkk.........',
    ],
    idleInhale: [
      '................................',
      '.............kkkkkk.............',
      '...........kkhhhhhhkk...........',
      '.........kklllllhhhhhkk.........',
      '........khlllhhhHhhhhHHk........',
      '.......khllhhhhhHhhhhhHHk.......',
      '......khllhhhhhhHhhhhhhHHk......',
      '......khhhhhhhhhHhhhhhhHHk......',
      '.....khhhhhhhHhhHhhHhhhhHHk.....',
      '.....khhhhhhHhhhHhhhHhHHHHk.....',
      '.....khhhhhHhhhhHhhhhHHHHHk.....',
      '...kkkhhhhHhhhhhHhhhhhHHHHkkk...',
      '..klhHhhhHhhhhhhHhhhhhHHHHHhhk..',
      '.kllhhHkkhhhhhhhHhhHHHHkkHhhhHk.',
      '.khhhHk..khHHHHHHHHHHHk..khhHHk.',
      '.khHHk....kSssssssSSSk....khHHk.',
      '..kHHk..kkkqSSSSSSSSpkkk..kHHk..',
      '...kk..kqqqqppppppppppppk..kk...',
      '......kpqqppppppppppppppPk......',
      '......kpppppppppppppppppPk......',
      '......kPPPppppppppppppPPPk......',
      '.......ksSPppppppppppPsSk.......',
      '.......ksSPppppppppppPsSk.......',
      '.......ksspPppppppppPpssk.......',
      '.......kSSJJJJJJJJJJJJSSk.......',
      '........kkjjjjjjjjjjjJkk........',
      '.........kjJJjjjjjJJjJk.........',
      '.........kjjjjjJJjjjjJk.........',
      '.........kjjjjjkkjjjjJk.........',
      '........keeeeek..keeeeek........',
      '........keeeeek..keeeeek........',
      '.........kkkkk....kkkkk.........',
    ],
    idleSettle: [
      '................................',
      '.............kkkkkk.............',
      '...........kkhhhhhhkk...........',
      '.........kklllllhhhhhkk.........',
      '........khlllhhhHhhhhHHk........',
      '.......khllhhhhhHhhhhhHHk.......',
      '......khllhhhhhhHhhhhhhHHk......',
      '......khhhhhhhhhHhhhhhhHHk......',
      '.....khhhhhhhHhhHhhHhhhhHHk.....',
      '.....khhhhhhHhhhHhhhHhHHHHk.....',
      '.....khhhhhHhhhhHhhhhHHHHHk.....',
      '.....khhhhHhhhhhHhhhhhHHHHk.....',
      '...kkHhhhHhhhhhhHhhhhhHHHHkkk...',
      '..klhHHkkhhhhhhhHhhHHHHkkkHhhk..',
      '.kllhhk..khHHHHHHHHHHHk..khhhHk.',
      '.khhhHk...kSssssssSSSk...khhHHk.',
      '.khHHk...kkqSSSSSSSSpkk...khHHk.',
      '..kHHk.kkqqqpppppppppppkk.kHHk..',
      '...kk.kpqqppppppppppppppPk.kk...',
      '......kpppppppppppppppppPk......',
      '......kPPPppppppppppppPPPk......',
      '.......ksSPppppppppppPsSk.......',
      '.......ksSPppppppppppPsSk.......',
      '.......ksspPppppppppPpssk.......',
      '.......kSSJJJJJJJJJJJJSSk.......',
      '........kkjjjjjjjjjjjJkk........',
      '.........kjJJjjjjjJJjJk.........',
      '.........kjjjjjJJjjjjJk.........',
      '.........kjjjjjkkjjjjJk.........',
      '........keeeeek..keeeeek........',
      '........keeeeek..keeeeek........',
      '.........kkkkk....kkkkk.........',
    ],
    walkContactA: [
      '................................',
      '.............kkkkkk.............',
      '...........kkhhhhhhkk...........',
      '.........kklllllhhhhhkk.........',
      '........khlllhhhHhhhhHHk........',
      '.......khllhhhhhHhhhhhHHk.......',
      '......khllhhhhhhHhhhhhhHHk......',
      '......khhhhhhhhhHhhhhhhHHk......',
      '.....khhhhhhhHhhHhhHhhhhHHk.....',
      '.....khhhhhhHhhhHhhhHhHHHHk.....',
      '.....khhhhhHhhhhHhhhhHHHHHk.....',
      '.....khhhhHhhhhhHhhhhhHHHHk.....',
      '...kkHhhhHhhhhhhHhhhhhHHHHkkk...',
      '..klhHHkkhhhhhhhHhhHHHHkkkHhhk..',
      '.kllhhk..khHHHHHHHHHHHk..khhhHk.',
      '.khhhHk...kSssssssSSSk...khhHHk.',
      '.khHHk...kkqSSSSSSSSpkk...khHHk.',
      '..kHHk.kkqqqpppppppppppkk.kHHk..',
      '...kk.kpqqppppppppppppppPk.kk...',
      '......kpppppppppppppppppPk......',
      '......kPPPppppppppppppPPPk......',
      '.......kssPppppppppppPsSk.......',
      '.......kssPppppppppppPsSk.......',
      '.......kSSpPppppppppPpsSk.......',
      '........kkJJJJJJJJJJJJssk.......',
      '.........kjjjjjjjjjjjJSSk.......',
      '.........kjJJjjjjjJJjJkk........',
      '.........kjjjjjJJjjjjJk.........',
      '.........kjjjjjkkkeeeeek........',
      '........keeeeek..keeeeek........',
      '........keeeeek...kkkkk.........',
      '.........kkkkk..................',
    ],
    walkPassing: [
      '................................',
      '................................',
      '.............kkkkkk.............',
      '...........kkhhhhhhkk...........',
      '.........kklllllhhhhhkk.........',
      '........khlllhhhHhhhhHHk........',
      '.......khllhhhhhHhhhhhHHk.......',
      '......khllhhhhhhHhhhhhhHHk......',
      '......khhhhhhhhhHhhhhhhHHk......',
      '.....khhhhhhhHhhHhhHhhhhHHk.....',
      '.....khhhhhhHhhhHhhhHhHHHHk.....',
      '...kkkhhhhhHhhhhHhhhhHHHHHkkk...',
      '..klhHhhhhHhhhhhHhhhhhHHHHHhhk..',
      '.kllhHhhhHhhhhhhHhhhhhHHHHHhhHk.',
      '.khhhHkkkhhhhhhhHhhHHHHkkkhhHHk.',
      '.khHHk...khHHHHHHHHHHHk...khHHk.',
      '..kHHk....kSssssssSSSk....kHHk..',
      '...kk....kkqSSSSSSSSpkk....kk...',
      '.......kkqqqpppppppppppkk.......',
      '......kpqqppppppppppppppPk......',
      '......kpppppppppppppppppPk......',
      '......kPPPppppppppppppPPPk......',
      '.......ksSPppppppppppPsSk.......',
      '.......ksSPppppppppppPsSk.......',
      '.......ksspPppppppppPpssk.......',
      '.......kSSJJJJJJJJJJJJSSk.......',
      '........kkjJJjjjjjJJjJkk........',
      '.........kjjjjjJJjjjjJk.........',
      '.........kjjjjjkkjjjjJk.........',
      '........keeeeek..keeeeek........',
      '........keeeeek..keeeeek........',
      '.........kkkkk....kkkkk.........',
    ],
    walkContactB: [
      '................................',
      '.............kkkkkk.............',
      '...........kkhhhhhhkk...........',
      '.........kklllllhhhhhkk.........',
      '........khlllhhhHhhhhHHk........',
      '.......khllhhhhhHhhhhhHHk.......',
      '......khllhhhhhhHhhhhhhHHk......',
      '......khhhhhhhhhHhhhhhhHHk......',
      '.....khhhhhhhHhhHhhHhhhhHHk.....',
      '.....khhhhhhHhhhHhhhHhHHHHk.....',
      '.....khhhhhHhhhhHhhhhHHHHHk.....',
      '.....khhhhHhhhhhHhhhhhHHHHk.....',
      '...kkHhhhHhhhhhhHhhhhhHHHHkkk...',
      '..klhHHkkhhhhhhhHhhHHHHkkkHhhk..',
      '.kllhhk..khHHHHHHHHHHHk..khhhHk.',
      '.khhhHk...kSssssssSSSk...khhHHk.',
      '.khHHk...kkqSSSSSSSSpkk...khHHk.',
      '..kHHk.kkqqqpppppppppppkk.kHHk..',
      '...kk.kpqqppppppppppppppPk.kk...',
      '......kpppppppppppppppppPk......',
      '......kPPPppppppppppppPPPk......',
      '.......ksSPppppppppppPssk.......',
      '.......ksSPppppppppppPssk.......',
      '.......ksSpPppppppppPpSSk.......',
      '.......kssJJJJJJJJJJJJkk........',
      '.......kSSjjjjjjjjjjjJk.........',
      '........kkjJJjjjjjJJjJk.........',
      '.........kjjjjjJJjjjjJk.........',
      '........keeeeekkkjjjjJk.........',
      '........keeeeek..keeeeek........',
      '.........kkkkk...keeeeek........',
      '..................kkkkk.........',
    ],
  },
  left: {
    idle: [
      '................................',
      '...........kkkkkkkk.............',
      '.........kkhhhhhhhhkk...........',
      '........khlllllhhhhHHkk.........',
      '.......khlllhhhhhhhhHHHk........',
      '......khllhhhhhhhhhhhHHHk.......',
      '......kllhhhhhhhhhhhhhHHHk......',
      '......khhhHhhhhhhhhhhhHHHk......',
      '......khhHHhhhhhhhhhhHHHHk......',
      '......kHHsHHsHhhhhhhhhHHHk......',
      '......ksseessHhhhhhhhhHHHk......',
      '.....kssseessHhhhhhhhhHHHkkk....',
      '......ksseessHhhhhhhhHHHHHhhk...',
      '......ksssttsHhhhhhhHHHkkhhhHk..',
      '.......kSSsssHHHHHHHHHk.khhHHk..',
      '........kssssssSHHHHkk...khHHk..',
      '.........kSSSSSSSPPPk....kHHk...',
      '.........kppqqqqqpppPk....kk....',
      '.........kppqppppppPPk..........',
      '.........kpppppppppPPk..........',
      '.........kppPPPPPPPPPk..........',
      '.........kppPpsSpppPPk..........',
      '.........kpppPsSppPPPk..........',
      '.........kppppsspppPPk..........',
      '.........kJJJJSSJJJJJk..........',
      '..........kjjjjjjjjJk...........',
      '...........kjjjjjjJk............',
      '...........kjjjjjjJk............',
      '...........kjjjjjjJk............',
      '...........keeeeeek.............',
      '..........keeeeeeek.............',
      '...........kkkkkkk..............',
    ],
    idleBlink: [
      '................................',
      '...........kkkkkkkk.............',
      '.........kkhhhhhhhhkk...........',
      '........khlllllhhhhHHkk.........',
      '.......khlllhhhhhhhhHHHk........',
      '......khllhhhhhhhhhhhHHHk.......',
      '......kllhhhhhhhhhhhhhHHHk......',
      '......khhhHhhhhhhhhhhhHHHk......',
      '......khhHHhhhhhhhhhhHHHHk......',
      '......kHHsHHsHhhhhhhhhHHHk......',
      '......kssssssHhhhhhhhhHHHk......',
      '.....ksssssssHhhhhhhhhHHHkkk....',
      '......ksseessHhhhhhhhHHHHHhhk...',
      '......ksssttsHhhhhhhHHHkkhhhHk..',
      '.......kSSsssHHHHHHHHHk.khhHHk..',
      '........kssssssSHHHHkk...khHHk..',
      '.........kSSSSSSSPPPk....kHHk...',
      '.........kppqqqqqpppPk....kk....',
      '.........kppqppppppPPk..........',
      '.........kpppppppppPPk..........',
      '.........kppPPPPPPPPPk..........',
      '.........kppPpsSpppPPk..........',
      '.........kpppPsSppPPPk..........',
      '.........kppppsspppPPk..........',
      '.........kJJJJSSJJJJJk..........',
      '..........kjjjjjjjjJk...........',
      '...........kjjjjjjJk............',
      '...........kjjjjjjJk............',
      '...........kjjjjjjJk............',
      '...........keeeeeek.............',
      '..........keeeeeeek.............',
      '...........kkkkkkk..............',
    ],
    idleInhale: [
      '................................',
      '...........kkkkkkkk.............',
      '.........kkhhhhhhhhkk...........',
      '........khlllllhhhhHHkk.........',
      '.......khlllhhhhhhhhHHHk........',
      '......khllhhhhhhhhhhhHHHk.......',
      '......kllhhhhhhhhhhhhhHHHk......',
      '......khhhHhhhhhhhhhhhHHHk......',
      '......khhHHhhhhhhhhhhHHHHk......',
      '......kHHsHHsHhhhhhhhhHHHk......',
      '......ksseessHhhhhhhhhHHHk......',
      '.....kssseessHhhhhhhhhHHHkkk....',
      '......ksseessHhhhhhhhHHHHHhhk...',
      '......ksssttsHhhhhhhHHHkkhhhHk..',
      '.......kSSsssHHHHHHHHHk.khhHHk..',
      '........kssssssSHHHHkk...khHHk..',
      '.........kSSSSSppPPPk....kHHk...',
      '.........kppqqqqqpppPk....kk....',
      '.........kppqppppppPPk..........',
      '.........kpppppppppPPk..........',
      '.........kppPPPPPPPPPk..........',
      '.........kppPpsSpppPPk..........',
      '.........kpppPsSppPPPk..........',
      '.........kppppsspppPPk..........',
      '.........kJJJJSSJJJJJk..........',
      '..........kjjjjjjjjJk...........',
      '...........kjjjjjjJk............',
      '...........kjjjjjjJk............',
      '...........kjjjjjjJk............',
      '...........keeeeeek.............',
      '..........keeeeeeek.............',
      '...........kkkkkkk..............',
    ],
    idleInhaleBlink: [
      '................................',
      '...........kkkkkkkk.............',
      '.........kkhhhhhhhhkk...........',
      '........khlllllhhhhHHkk.........',
      '.......khlllhhhhhhhhHHHk........',
      '......khllhhhhhhhhhhhHHHk.......',
      '......kllhhhhhhhhhhhhhHHHk......',
      '......khhhHhhhhhhhhhhhHHHk......',
      '......khhHHhhhhhhhhhhHHHHk......',
      '......kHHsHHsHhhhhhhhhHHHk......',
      '......kssssssHhhhhhhhhHHHk......',
      '.....ksssssssHhhhhhhhhHHHkkk....',
      '......ksseessHhhhhhhhHHHHHhhk...',
      '......ksssttsHhhhhhhHHHkkhhhHk..',
      '.......kSSsssHHHHHHHHHk.khhHHk..',
      '........kssssssSHHHHkk...khHHk..',
      '.........kSSSSSppPPPk....kHHk...',
      '.........kppqqqqqpppPk....kk....',
      '.........kppqppppppPPk..........',
      '.........kpppppppppPPk..........',
      '.........kppPPPPPPPPPk..........',
      '.........kppPpsSpppPPk..........',
      '.........kpppPsSppPPPk..........',
      '.........kppppsspppPPk..........',
      '.........kJJJJSSJJJJJk..........',
      '..........kjjjjjjjjJk...........',
      '...........kjjjjjjJk............',
      '...........kjjjjjjJk............',
      '...........kjjjjjjJk............',
      '...........keeeeeek.............',
      '..........keeeeeeek.............',
      '...........kkkkkkk..............',
    ],
    idleSettle: [
      '................................',
      '...........kkkkkkkk.............',
      '.........kkhhhhhhhhkk...........',
      '........khlllllhhhhHHkk.........',
      '.......khlllhhhhhhhhHHHk........',
      '......khllhhhhhhhhhhhHHHk.......',
      '......kllhhhhhhhhhhhhhHHHk......',
      '......khhhHhhhhhhhhhhhHHHk......',
      '......khhHHhhhhhhhhhhHHHHk......',
      '......kHHsHHsHhhhhhhhhHHHk......',
      '......ksseessHhhhhhhhhHHHk......',
      '.....kssseessHhhhhhhhhHHHk......',
      '......ksseessHhhhhhhhHHHk.kk....',
      '......ksssttsHhhhhhhHHHk.khhk...',
      '.......kSSsssHHHHHHHHHk.khhhHk..',
      '........kssssssSHHHHkk..khhHHk..',
      '.........kSSSSSSSPPPk....khHHk..',
      '.........kppqqqqqpppPk...kHHk...',
      '.........kppqppppppPPk....kk....',
      '.........kpppppppppPPk..........',
      '.........kppPPPPPPPPPk..........',
      '.........kppPpsSpppPPk..........',
      '.........kpppPsSppPPPk..........',
      '.........kppppsspppPPk..........',
      '.........kJJJJSSJJJJJk..........',
      '..........kjjjjjjjjJk...........',
      '...........kjjjjjjJk............',
      '...........kjjjjjjJk............',
      '...........kjjjjjjJk............',
      '...........keeeeeek.............',
      '..........keeeeeeek.............',
      '...........kkkkkkk..............',
    ],
    walkContactA: [
      '................................',
      '...........kkkkkkkk.............',
      '.........kkhhhhhhhhkk...........',
      '........khlllllhhhhHHkk.........',
      '.......khlllhhhhhhhhHHHk........',
      '......khllhhhhhhhhhhhHHHk.......',
      '......kllhhhhhhhhhhhhhHHHk......',
      '......khhhHhhhhhhhhhhhHHHk......',
      '......khhHHhhhhhhhhhhHHHHk......',
      '......kHHsHHsHhhhhhhhhHHHk......',
      '......ksseessHhhhhhhhhHHHk......',
      '.....kssseessHhhhhhhhhHHHk......',
      '......ksseessHhhhhhhhHHHk.kk....',
      '......ksssttsHhhhhhhHHHk.khhk...',
      '.......kSSsssHHHHHHHHHk.khhhHk..',
      '........kssssssSHHHHkk..khhHHk..',
      '.........kSSSSSSSPPPk....khHHk..',
      '.........kppqqqqqpppPk...kHHk...',
      '.........kppqppppppPPk....kk....',
      '.........kpppppppppPPk..........',
      '.........kppPPPPPPPPPk..........',
      '.........kppPppsSppPPk..........',
      '.........kpppPpsSpPPPk..........',
      '.........kpppppssppPPk..........',
      '.........kJJJJJSSJJJJk..........',
      '..........kjjjjjjjjJk...........',
      '..........kjjjjjJJJJk...........',
      '.........kjjjjjkkJJJJk..........',
      '........kjjjjjk..kJJJJk.........',
      '.......keeeeeek.keeeeeek........',
      '......keeeeeeekkeeeeeeek........',
      '.......kkkkkkk..kkkkkkk.........',
    ],
    walkPassing: [
      '................................',
      '................................',
      '...........kkkkkkkk.............',
      '.........kkhhhhhhhhkk...........',
      '........khlllllhhhhHHkk.........',
      '.......khlllhhhhhhhhHHHk........',
      '......khllhhhhhhhhhhhHHHk.......',
      '......kllhhhhhhhhhhhhhHHHk......',
      '......khhhHhhhhhhhhhhhHHHk......',
      '......khhHHhhhhhhhhhhHHHHk......',
      '......kHHsHHsHhhhhhhhhHHHk......',
      '......ksseessHhhhhhhhhHHHkkk....',
      '.....kssseessHhhhhhhhhHHHHhhk...',
      '......ksseessHhhhhhhhHHHHhhhHk..',
      '......ksssttsHhhhhhhHHHkkhhHHk..',
      '.......kSSsssHHHHHHHHHk..khHHk..',
      '........kssssssSHHHHkk...kHHk...',
      '.........kSSSSSSSPPPk.....kk....',
      '.........kppqqqqqpppPk..........',
      '.........kppqppppppPPk..........',
      '.........kpppppppppPPk..........',
      '.........kppPPPPPPPPPk..........',
      '.........kppPpsSpppPPk..........',
      '.........kpppPsSppPPPk..........',
      '.........kppppsspppPPk..........',
      '.........kkJJJSSJJJJkk..........',
      '...........kjjjjjjJk............',
      '...........kjjjjjjJk............',
      '...........kjjjjjjJk............',
      '...........keeeeeek.............',
      '..........keeeeeeek.............',
      '...........kkkkkkk..............',
    ],
    walkContactB: [
      '................................',
      '...........kkkkkkkk.............',
      '.........kkhhhhhhhhkk...........',
      '........khlllllhhhhHHkk.........',
      '.......khlllhhhhhhhhHHHk........',
      '......khllhhhhhhhhhhhHHHk.......',
      '......kllhhhhhhhhhhhhhHHHk......',
      '......khhhHhhhhhhhhhhhHHHk......',
      '......khhHHhhhhhhhhhhHHHHk......',
      '......kHHsHHsHhhhhhhhhHHHk......',
      '......ksseessHhhhhhhhhHHHk......',
      '.....kssseessHhhhhhhhhHHHk......',
      '......ksseessHhhhhhhhHHHk.kk....',
      '......ksssttsHhhhhhhHHHk.khhk...',
      '.......kSSsssHHHHHHHHHk.khhhHk..',
      '........kssssssSHHHHkk..khhHHk..',
      '.........kSSSSSSSPPPk....khHHk..',
      '.........kppqqqqqpppPk...kHHk...',
      '.........kppqppppppPPk....kk....',
      '.........kpppppppppPPk..........',
      '.........kppPPPPPPPPPk..........',
      '.........kppPsSppppPPk..........',
      '.........kpppsSpppPPPk..........',
      '.........kpppssppppPPk..........',
      '.........kJJJSSJJJJJJk..........',
      '..........kjjjjjjjjJk...........',
      '..........kJJJJJjjjJk...........',
      '.........kJJJJJkkjjjJk..........',
      '........kJJJJJk..kjjjJk.........',
      '.......keeeeeek.keeeeeek........',
      '......keeeeeeekkeeeeeeek........',
      '.......kkkkkkk..kkkkkkk.........',
    ],
  },
  right: {
    idle: [
      '................................',
      '.............kkkkkkkk...........',
      '...........kkhhhhhhhhkk.........',
      '.........kkllllllhhhhHHk........',
      '........khlllhhhhhhhhHHHk.......',
      '.......khllhhhhhhhhhhhHHHk......',
      '......kllhhhhhhhhhhhhhHHHk......',
      '......khhhhhhhhhhhhhhHhHHk......',
      '......khhhhhhhhhhhhhhHHHHk......',
      '......khhhhhhhhhhhHsHHsHHk......',
      '......khhhhhhhhhhhHsseessk......',
      '....kkkhhhhhhhhhhhHsseesssk.....',
      '...klhHHhhhhhhhhhhHsseessk......',
      '..kllhhkkhhhhhhhhhHsttsssk......',
      '..khhhHk.kHHHHHHHHHsssSSk.......',
      '..khHHk...kkHHHHSsssssSk........',
      '...kHHk....kPPPSSSSSSSk.........',
      '....kk....kppqqqqqpppPk.........',
      '..........kppqppppppPPk.........',
      '..........kpppppppppPPk.........',
      '..........kppPPPPPPPPPk.........',
      '..........kpppppsSpPPPk.........',
      '..........kpppppsSPpPPk.........',
      '..........kpppppssppPPk.........',
      '..........kJJJJJSSJJJJk.........',
      '...........kjjjjjjjjJk..........',
      '............kjjjjjjJk...........',
      '............kjjjjjjJk...........',
      '............kjjjjjjJk...........',
      '.............keeeeeek...........',
      '.............keeeeeeek..........',
      '..............kkkkkkk...........',
    ],
    idleBlink: [
      '................................',
      '.............kkkkkkkk...........',
      '...........kkhhhhhhhhkk.........',
      '.........kkllllllhhhhHHk........',
      '........khlllhhhhhhhhHHHk.......',
      '.......khllhhhhhhhhhhhHHHk......',
      '......kllhhhhhhhhhhhhhHHHk......',
      '......khhhhhhhhhhhhhhHhHHk......',
      '......khhhhhhhhhhhhhhHHHHk......',
      '......khhhhhhhhhhhHsHHsHHk......',
      '......khhhhhhhhhhhHssssssk......',
      '....kkkhhhhhhhhhhhHsssssssk.....',
      '...klhHHhhhhhhhhhhHsseessk......',
      '..kllhhkkhhhhhhhhhHsttsssk......',
      '..khhhHk.kHHHHHHHHHsssSSk.......',
      '..khHHk...kkHHHHSsssssSk........',
      '...kHHk....kPPPSSSSSSSk.........',
      '....kk....kppqqqqqpppPk.........',
      '..........kppqppppppPPk.........',
      '..........kpppppppppPPk.........',
      '..........kppPPPPPPPPPk.........',
      '..........kpppppsSpPPPk.........',
      '..........kpppppsSPpPPk.........',
      '..........kpppppssppPPk.........',
      '..........kJJJJJSSJJJJk.........',
      '...........kjjjjjjjjJk..........',
      '............kjjjjjjJk...........',
      '............kjjjjjjJk...........',
      '............kjjjjjjJk...........',
      '.............keeeeeek...........',
      '.............keeeeeeek..........',
      '..............kkkkkkk...........',
    ],
    idleInhale: [
      '................................',
      '.............kkkkkkkk...........',
      '...........kkhhhhhhhhkk.........',
      '.........kkllllllhhhhHHk........',
      '........khlllhhhhhhhhHHHk.......',
      '.......khllhhhhhhhhhhhHHHk......',
      '......kllhhhhhhhhhhhhhHHHk......',
      '......khhhhhhhhhhhhhhHhHHk......',
      '......khhhhhhhhhhhhhhHHHHk......',
      '......khhhhhhhhhhhHsHHsHHk......',
      '......khhhhhhhhhhhHsseessk......',
      '....kkkhhhhhhhhhhhHsseesssk.....',
      '...klhHHhhhhhhhhhhHsseessk......',
      '..kllhhkkhhhhhhhhhHsttsssk......',
      '..khhhHk.kHHHHHHHHHsssSSk.......',
      '..khHHk...kkHHHHSsssssSk........',
      '...kHHk....kPPPppSSSSSk.........',
      '....kk....kppqqqqqpppPk.........',
      '..........kppqppppppPPk.........',
      '..........kpppppppppPPk.........',
      '..........kppPPPPPPPPPk.........',
      '..........kpppppsSpPPPk.........',
      '..........kpppppsSPpPPk.........',
      '..........kpppppssppPPk.........',
      '..........kJJJJJSSJJJJk.........',
      '...........kjjjjjjjjJk..........',
      '............kjjjjjjJk...........',
      '............kjjjjjjJk...........',
      '............kjjjjjjJk...........',
      '.............keeeeeek...........',
      '.............keeeeeeek..........',
      '..............kkkkkkk...........',
    ],
    idleInhaleBlink: [
      '................................',
      '.............kkkkkkkk...........',
      '...........kkhhhhhhhhkk.........',
      '.........kkllllllhhhhHHk........',
      '........khlllhhhhhhhhHHHk.......',
      '.......khllhhhhhhhhhhhHHHk......',
      '......kllhhhhhhhhhhhhhHHHk......',
      '......khhhhhhhhhhhhhhHhHHk......',
      '......khhhhhhhhhhhhhhHHHHk......',
      '......khhhhhhhhhhhHsHHsHHk......',
      '......khhhhhhhhhhhHssssssk......',
      '....kkkhhhhhhhhhhhHsssssssk.....',
      '...klhHHhhhhhhhhhhHsseessk......',
      '..kllhhkkhhhhhhhhhHsttsssk......',
      '..khhhHk.kHHHHHHHHHsssSSk.......',
      '..khHHk...kkHHHHSsssssSk........',
      '...kHHk....kPPPppSSSSSk.........',
      '....kk....kppqqqqqpppPk.........',
      '..........kppqppppppPPk.........',
      '..........kpppppppppPPk.........',
      '..........kppPPPPPPPPPk.........',
      '..........kpppppsSpPPPk.........',
      '..........kpppppsSPpPPk.........',
      '..........kpppppssppPPk.........',
      '..........kJJJJJSSJJJJk.........',
      '...........kjjjjjjjjJk..........',
      '............kjjjjjjJk...........',
      '............kjjjjjjJk...........',
      '............kjjjjjjJk...........',
      '.............keeeeeek...........',
      '.............keeeeeeek..........',
      '..............kkkkkkk...........',
    ],
    idleSettle: [
      '................................',
      '.............kkkkkkkk...........',
      '...........kkhhhhhhhhkk.........',
      '.........kkllllllhhhhHHk........',
      '........khlllhhhhhhhhHHHk.......',
      '.......khllhhhhhhhhhhhHHHk......',
      '......kllhhhhhhhhhhhhhHHHk......',
      '......khhhhhhhhhhhhhhHhHHk......',
      '......khhhhhhhhhhhhhhHHHHk......',
      '......khhhhhhhhhhhHsHHsHHk......',
      '......khhhhhhhhhhhHsseessk......',
      '......khhhhhhhhhhhHsseesssk.....',
      '....kk.khhhhhhhhhhHsseessk......',
      '...klhk.khhhhhhhhhHsttsssk......',
      '..kllhhk.kHHHHHHHHHsssSSk.......',
      '..khhhHk..kkHHHHSsssssSk........',
      '..khHHk....kPPPSSSSSSSk.........',
      '...kHHk...kppqqqqqpppPk.........',
      '....kk....kppqppppppPPk.........',
      '..........kpppppppppPPk.........',
      '..........kppPPPPPPPPPk.........',
      '..........kpppppsSpPPPk.........',
      '..........kpppppsSPpPPk.........',
      '..........kpppppssppPPk.........',
      '..........kJJJJJSSJJJJk.........',
      '...........kjjjjjjjjJk..........',
      '............kjjjjjjJk...........',
      '............kjjjjjjJk...........',
      '............kjjjjjjJk...........',
      '.............keeeeeek...........',
      '.............keeeeeeek..........',
      '..............kkkkkkk...........',
    ],
    walkContactA: [
      '................................',
      '.............kkkkkkkk...........',
      '...........kkhhhhhhhhkk.........',
      '.........kkllllllhhhhHHk........',
      '........khlllhhhhhhhhHHHk.......',
      '.......khllhhhhhhhhhhhHHHk......',
      '......kllhhhhhhhhhhhhhHHHk......',
      '......khhhhhhhhhhhhhhHhHHk......',
      '......khhhhhhhhhhhhhhHHHHk......',
      '......khhhhhhhhhhhHsHHsHHk......',
      '......khhhhhhhhhhhHsseessk......',
      '......khhhhhhhhhhhHsseesssk.....',
      '....kk.khhhhhhhhhhHsseessk......',
      '...klhk.khhhhhhhhhHsttsssk......',
      '..kllhhk.kHHHHHHHHHsssSSk.......',
      '..khhhHk..kkHHHHSsssssSk........',
      '..khHHk....kPPPSSSSSSSk.........',
      '...kHHk...kppqqqqqpppPk.........',
      '....kk....kppqppppppPPk.........',
      '..........kpppppppppPPk.........',
      '..........kppPPPPPPPPPk.........',
      '..........kppppsSppPPPk.........',
      '..........kppppsSpPpPPk.........',
      '..........kppppsspppPPk.........',
      '..........kJJJJSSJJJJJk.........',
      '...........kjjjjjjjjJk..........',
      '...........kJJJJjjjjjk..........',
      '..........kJJJJkkjjjjjk.........',
      '.........kJJJJk..kjjjjjk........',
      '........keeeeeek.keeeeeek.......',
      '........keeeeeeekkeeeeeeek......',
      '.........kkkkkkk..kkkkkkk.......',
    ],
    walkPassing: [
      '................................',
      '................................',
      '.............kkkkkkkk...........',
      '...........kkhhhhhhhhkk.........',
      '.........kkllllllhhhhHHk........',
      '........khlllhhhhhhhhHHHk.......',
      '.......khllhhhhhhhhhhhHHHk......',
      '......kllhhhhhhhhhhhhhHHHk......',
      '......khhhhhhhhhhhhhhHhHHk......',
      '......khhhhhhhhhhhhhhHHHHk......',
      '......khhhhhhhhhhhHsHHsHHk......',
      '....kkkhhhhhhhhhhhHsseessk......',
      '...klhHhhhhhhhhhhhHsseesssk.....',
      '..kllhhHhhhhhhhhhhHsseessk......',
      '..khhhHkkhhhhhhhhhHsttsssk......',
      '..khHHk..kHHHHHHHHHsssSSk.......',
      '...kHHk...kkHHHHSsssssSk........',
      '....kk.....kPPPSSSSSSSk.........',
      '..........kppqqqqqpppPk.........',
      '..........kppqppppppPPk.........',
      '..........kpppppppppPPk.........',
      '..........kppPPPPPPPPPk.........',
      '..........kpppppsSpPPPk.........',
      '..........kpppppsSPpPPk.........',
      '..........kpppppssppPPk.........',
      '..........kkJJJJSSJJJkk.........',
      '............kjjjjjjJk...........',
      '............kjjjjjjJk...........',
      '............kjjjjjjJk...........',
      '.............keeeeeek...........',
      '.............keeeeeeek..........',
      '..............kkkkkkk...........',
    ],
    walkContactB: [
      '................................',
      '.............kkkkkkkk...........',
      '...........kkhhhhhhhhkk.........',
      '.........kkllllllhhhhHHk........',
      '........khlllhhhhhhhhHHHk.......',
      '.......khllhhhhhhhhhhhHHHk......',
      '......kllhhhhhhhhhhhhhHHHk......',
      '......khhhhhhhhhhhhhhHhHHk......',
      '......khhhhhhhhhhhhhhHHHHk......',
      '......khhhhhhhhhhhHsHHsHHk......',
      '......khhhhhhhhhhhHsseessk......',
      '......khhhhhhhhhhhHsseesssk.....',
      '....kk.khhhhhhhhhhHsseessk......',
      '...klhk.khhhhhhhhhHsttsssk......',
      '..kllhhk.kHHHHHHHHHsssSSk.......',
      '..khhhHk..kkHHHHSsssssSk........',
      '..khHHk....kPPPSSSSSSSk.........',
      '...kHHk...kppqqqqqpppPk.........',
      '....kk....kppqppppppPPk.........',
      '..........kpppppppppPPk.........',
      '..........kppPPPPPPPPPk.........',
      '..........kppppppsSPPPk.........',
      '..........kppppppsSpPPk.........',
      '..........kppppppsspPPk.........',
      '..........kJJJJJJSSJJJk.........',
      '...........kjjjjjjjjJk..........',
      '...........kJjjjJJJJJk..........',
      '..........kJjjjkkJJJJJk.........',
      '.........kJjjjk..kJJJJJk........',
      '........keeeeeek.keeeeeek.......',
      '........keeeeeeekkeeeeeeek......',
      '.........kkkkkkk..kkkkkkk.......',
    ],
  },
};

const heroHold = [
  '...kkkk.....kkkkkkkk.....kkkk...',
  '..kssssk..kkllllllhhkk..kssssk..',
  '..kssssk.klllllllhhhhHk.kssssk..',
  '..ksssskkllllllhhhhhhHHkkssssk..',
  '..kSSSSkklllhhhhhhhhhhHkkSSSSk..',
  '...kssSklhhhhhhhhhhhhhHHkssSk...',
  '...kssSkhhhhhhhhhhhhhHHHkssSk...',
  '...kssSkhhhhhhhhhhhhhHHHkssSk...',
  '...kssSkhhHhhHHhhHhhHHHHkssSk...',
  '...kssSkhtsscesssscessSHkssSk...',
  '...kssSkhtsseesssseessSHkssSk...',
  '...kssSkhtsseesssseessSHkssSk...',
  '...kqqqkHsqqssseesssqqSHkpPPk...',
  '..kqqqqpkkssssssssssSSkkppPPPk..',
  '..kqqqqqpkkkkkSSSSkkkkkppPPPPk..',
  '..kkqqqqqqqqqPSSSSPppPPPPPPPkk..',
  '....kkqqqqppppPPpppppPPPPPkk....',
  '......kkqqpppppppppppPPPkk......',
  '........kkppppqpqpppPPkk........',
  '..........kpPpqqqpPpPk..........',
  '..........kpPppqppPpPk..........',
  '..........kpPpppppPpPk..........',
  '..........kJJJJJJJJJJk..........',
  '..........kjjjjjjjjjJk..........',
  '..........kjjjjJJjjjJk..........',
  '..........kjjjJkkjjjJk..........',
  '..........kjjjJkkjjjJk..........',
  '..........kbbbbkkbbbbk..........',
  '.........kbbbbbkkbbbbbk.........',
  '.........kbbbbbkkbbbbbk.........',
  '.........kbbbbbkkbbbbbk.........',
  '..........kkkkk..kkkkk..........',
];

// Holding up keeps the head of the earlier back view until a holding pose is drawn for the current one.
const heroHoldUp = [
  '...kkkk.....kkkkkkkk.....kkkk...',
  '..kssssk..kkllllllhhkk..kssssk..',
  '..kssssk.klllllHhhhhhHk.kssssk..',
  '..ksssskkllllllHhhhhhHHkkssssk..',
  '..kSSSSkklllhhhHhhhhhhHkkSSSSk..',
  '...kssSklhhhhhhHhhhhhhHHkssSk...',
  '...kssSkhhhhhhhHhhhhhHHHkssSk...',
  '...kssSkhhhhhhhHhhhhhHHHkssSk...',
  '...kssSkhhhhhhhHhhhhhHHHkssSk...',
  '...kssSkhhhhhhhHhhhhHHHHkssSk...',
  '...kssSkhhhhhhhHhhhhHHHHkssSk...',
  '...kssSkHhhhhhhHhhhhHHHHkssSk...',
  '...kqqqkHHhhhhhHhhhHHHHHkpPPk...',
  '..kqqqqpkkHHHHHHHHHHHHkkppPPPk..',
  '..kqqqqqpkkkkkSSSSkkkkkppPPPPk..',
  '..kkqqqqqqqqqPSSSSPppPPPPPPPkk..',
  '....kkqqqqppppPPpppppPPPPPkk....',
  '......kkqqpppppppppppPPPkk......',
  '........kkppppppppppPPkk........',
  '..........kpPpppppPpPk..........',
  '..........kpPpppppPpPk..........',
  '..........kpPpppppPpPk..........',
  '..........kJJJJJJJJJJk..........',
  '..........kjjjjjjjjjJk..........',
  '..........kjjjjJJjjjJk..........',
  '..........kjjjJkkjjjJk..........',
  '..........kjjjJkkjjjJk..........',
  '..........kbbbbkkbbbbk..........',
  '.........kbbbbbkkbbbbbk.........',
  '.........kbbbbbkkbbbbbk.........',
  '.........kbbbbbkkbbbbbk.........',
  '..........kkkkk..kkkkk..........',
];

const heroHolding: Record<Facing, Grid> = { down: heroHold, up: heroHoldUp, left: heroHold, right: heroHold };

const build = (rows: Grid): Art => ({ legend: heroColors, rows });

function heroDirection(facing: Facing): HeroDirectionArt {
  const frames = heroFrames[facing];
  const passing = build(frames.walkPassing);
  return {
    stand: build(frames.idle),
    settle: build(frames.idleSettle),
    breathe: build(frames.idleInhale),
    blink: frames.idleBlink ? build(frames.idleBlink) : null,
    inhaleBlink: frames.idleInhaleBlink ? build(frames.idleInhaleBlink) : null,
    walk: [build(frames.walkContactA), passing, build(frames.walkContactB), passing],
    holding: build(heroHolding[facing]),
  };
}

export const heroArt: HeroArt = { down: heroDirection('down'), up: heroDirection('up'), left: heroDirection('left'), right: heroDirection('right') };
export const heroHoldingArt = heroArt.down.holding!;

const stoneShapes = [
  [ // rounded boulder
    '...........kkkkkkkk.............',
    '.........kkccccaaaakk...........',
    '........kccccaaaaaaaak..........',
    '.......kcccaaaaaaaaaaakk........',
    '......kccaaaaaaaaaaaaaaak.......',
    '.....kccaaaaaaaaaaaaaaaaak......',
    '.....kcaaaaaaaaaaaaaaaaabk......',
    '....kcaaaaaaaaaaaaaaaaaabbk.....',
    '....kaaaaaaaaaaaaaaaaaabbbk.....',
    '....kbaaaaaaaaaaaaaaaabbbbk.....',
    '....kbbbaaaaaaaaaaaaabbbbbk.....',
    '....kbbbbbbaaaaaaaabbbbbbbk.....',
    '.....kbbbbbbbbbbbbbbbbbbbk......',
    '.....kbbbbbbbbbbbbbbbbbbbk......',
    '......kbbbbbbbbbbbbbbbbbk.......',
    '.......kkbbbbbbbbbbbbbkk........',
    '.........kkkkkkkkkkkkk..........',
  ],
  [ // flat slab
    '..........kkkkkkkkkk............',
    '.......kkkccccaaaaaakkk.........',
    '.....kkccccaaaaaaaaaaaakk.......',
    '....kccccaaaaaaaaaaaaaaaak......',
    '...kccaaaaaaaaaaaaaaaaaaaak.....',
    '...kcaaaaaaaaaaaaaaaaaaaaabk....',
    '...kaaaaaaaaaaaaaaaaaaaaabbk....',
    '...kbbaaaaaaaaaaaaaaaaaabbbk....',
    '...kbbbbbbbbbbbbbbbbbbbbbbbk....',
    '...kbbbbbbbbbbbbbbbbbbbbbbbk....',
    '....kbbbbbbbbbbbbbbbbbbbbbk.....',
    '....kbbbbbbbbbbbbbbbbbbbbbk.....',
    '.....kkbbbbbbbbbbbbbbbbbkk......',
    '.......kkkkkkkkkkkkkkkkk........',
  ],
  [ // pointed rock
    '..............kkkk..............',
    '............kkccaak.............',
    '...........kcccaaaak............',
    '..........kcccaaaaaak...........',
    '.........kccaaaaaaaaak..........',
    '.........kcaaaaaaaaaaak.........',
    '........kccaaaaaaaaaaabk........',
    '........kcaaaaaaaaaaaabk........',
    '.......kcaaaaaaaaaaaaabbk.......',
    '.......kcaaaaaaaaaaaaabbk.......',
    '......kcaaaaaaaaaaaaaabbbk......',
    '......kaaaaaaaaaaaaaaabbbk......',
    '.....kbaaaaaaaaaaaaaaabbbbk.....',
    '.....kbbaaaaaaaaaaaaabbbbbk.....',
    '.....kbbbbaaaaaaaaabbbbbbbk.....',
    '.....kbbbbbbbbbbbbbbbbbbbbk.....',
    '......kbbbbbbbbbbbbbbbbbbk......',
    '......kbbbbbbbbbbbbbbbbbbk......',
    '.......kkbbbbbbbbbbbbbbkk.......',
    '.........kkkkkkkkkkkkkk.........',
  ],
];
// Every stone ends on row 26 so its ground shadow shows as a contact band directly beneath it.
const stoneTops = [10, 12, 7];

// Each variant pairs a shape with its own crack, so neighbors never repeat even when they share an outline.
const stoneDetails: readonly { shape: number; crack: readonly (readonly [number, number])[]; chips?: readonly (readonly [number, number, string])[] }[] = [
  { shape: 0, crack: [[10, 15], [11, 15], [12, 16], [13, 16], [14, 17], [15, 17], [16, 18]] },
  { shape: 1, crack: [[7, 17], [8, 17], [9, 17], [10, 16], [11, 16], [12, 16]] },
  { shape: 2, crack: [[12, 13], [13, 14], [14, 15], [15, 16], [16, 17], [17, 18]] },
  {
    shape: 0,
    crack: [[13, 14], [14, 14], [15, 14], [16, 15], [17, 15], [18, 15]],
    chips: [[19, 11, '.'], [20, 11, '.'], [18, 11, 'k'], [19, 12, 'k'], [20, 12, 'k']],
  },
  { shape: 1, crack: [[15, 15], [16, 15], [17, 16], [18, 16], [19, 17], [20, 17]] },
];

function stone({ shape, crack, chips = [] }: (typeof stoneDetails)[number]): Art {
  const grid = new PixelGrid(32, 32);
  stoneShapes[shape]!.forEach((line, row) => [...line].forEach((symbol, column) => {
    if (symbol !== '.') grid.put(column, row + stoneTops[shape]!, symbol);
  }));
  for (const [column, row] of crack) if (grid.get(column, row) === 'a') grid.put(column, row, 'b');
  for (const [column, row, symbol] of chips) grid.put(column, row, symbol);
  return grid.build(stoneColors);
}

export const stoneVariants = stoneDetails.map(stone);
export const stoneArt = stoneVariants[0]!;

const orbSymbols = {
  triangle: ['...x...', '..xxx..', '.xxxxx.', 'xxxxxxx'],
  cross: ['..xx..', '..xx..', 'xxxxxx', 'xxxxxx', '..xx..', '..xx..'],
  diamond: ['..xx..', '.xxxx.', 'xxxxxx', 'xxxxxx', '.xxxx.', '..xx..'],
  square: ['xxxxxx', 'xxxxxx', 'xx..xx', 'xx..xx', 'xxxxxx', 'xxxxxx'],
} as const;

function orb(legend: Legend, symbol: keyof typeof orbSymbols): Art {
  const grid = new PixelGrid(24, 24);
  const radius = 8;
  // Hand-set row widths keep the circle round at this size, where a computed one turns octagonal.
  const widths = [6, 10, 12, 14, 14, 16, 16, 16, 16, 16, 16, 14, 14, 12, 10, 6];
  const inside = (column: number, row: number): boolean => Math.abs(column - 11.5) < (widths[row - 4] ?? 0) / 2;
  for (let row = 0; row < 24; row++) {
    for (let column = 0; column < 24; column++) {
      if (!inside(column, row)) continue;
      const across = (column - 11.5) / radius;
      const down = (row - 11.5) / radius;
      const toward = Math.sqrt(Math.max(0, 1 - across ** 2 - down ** 2));
      // Lighting a true sphere from the top left gives the curved terminator the style asks for instead of a ring of shading.
      const light = -0.45 * across - 0.55 * down + 0.7 * toward;
      const edge = [[column - 1, row], [column + 1, row], [column, row - 1], [column, row + 1]].some(([x, y]) => !inside(x!, y!));
      grid.put(column, row, edge ? 'k' : light > 0.38 ? 'a' : 'b');
    }
  }
  // A small hard highlight and a faint bounce light on the far rim are what make the sphere read as glass.
  for (const [column, row] of [[7, 6], [8, 6], [9, 6], [6, 7], [7, 7], [6, 8]] as const) grid.put(column, row, 'c');
  for (const [column, row] of [[15, 16], [16, 15], [17, 14]] as const) grid.put(column, row, 'a');
  const shape = orbSymbols[symbol];
  const left = 12 - Math.ceil(shape[0]!.length / 2);
  const top = 12 - Math.floor(shape.length / 2);
  const carved = (column: number, row: number): boolean => shape[row - top]?.[column - left] === 'x';
  for (let row = top; row <= top + shape.length; row++) {
    for (let column = left; column <= left + shape[0]!.length; column++) {
      if (carved(column, row)) grid.put(column, row, 'c');
      // An engraved symbol catches a shadow on its lower right edge, so it sits in the glass rather than floating on it.
      else if (carved(column - 1, row - 1)) grid.put(column, row, 'b');
    }
  }
  return grid.build(legend);
}

export const orbArt = {
  red: orb({ k: 'Ink', a: 'R2', b: 'R1', c: 'R3' }, 'triangle'),
  blue: orb({ k: 'Ink', a: 'W2', b: 'W1', c: 'W3' }, 'cross'),
  violet: orb({ k: 'Ink', a: 'V2', b: 'V1', c: 'V3' }, 'diamond'),
  teal: orb({ k: 'Ink', a: 'T2', b: 'T1', c: 'T3' }, 'square'),
} as const;
export const violetOrbArt = orbArt.violet;

export const lightMote: Art = { legend: { p: 'Paper' }, rows: ['p'] };

export function groundShadow(width: number, code: 'G1' | 'E2' | 'N2'): Art {
  const grid = new PixelGrid(width, 5);
  grid.rectangle(0, 0, width, 1, 'd');
  grid.rectangle(2, 1, width - 4, 3, 'd');
  grid.rectangle(4, 4, width - 8, 1, 'd');
  return grid.build({ d: code });
}

export const heroShadowArt = { grass: groundShadow(14, 'G1'), path: groundShadow(14, 'E2') };

// A computed star turns spiky and uneven at this size, so its outline is drawn by hand.
const starShape = [
  '.......kk.......',
  '......kaak......',
  '......kaak......',
  '.....kaaaak.....',
  '.....kaaaak.....',
  'kkkkkaaaaaakkkkk',
  'kaaaaaaaaaaaaaak',
  '.kaaaaaaaaaaaak.',
  '..kaaaaaaaaaak..',
  '...kaaaaaaaak...',
  '...kaaaaaaaak...',
  '..kaaaaaaaaaak..',
  '..kaaaakkaaaak..',
  '.kaaakk..kkaaak.',
  '.kaak......kaak.',
  '.kkk........kkk.',
];

function star(): Art {
  const grid = new PixelGrid(24, 24);
  starShape.forEach((line, row) => [...line].forEach((pixel, column) => {
    // Shading the half below the diagonal through the center keeps the dark side on the bottom right, away from the light.
    if (pixel !== '.') grid.put(column + 4, row + 4, pixel === 'k' ? 'k' : column + row >= 18 ? 'b' : 'a');
  }));
  for (const [column, row] of [[7, 2], [7, 3], [2, 6], [3, 6]] as const) grid.put(column + 4, row + 4, 'c');
  return grid.build({ k: 'Ink', a: 'Y2', b: 'Y1', c: 'Y3' });
}

export const starArt = star();
