(globalThis.sprites ??= {}).grass = {
  legend: {
    g: 'G2',
    G: 'G3',
    d: 'G1',
  },
  frames: {
    'variant-0': [
      'gggggggggggggggggggggggggggggggg',
      'gggggggggggggGgggGggGggGgggggggg',
      'gggggggggGggggGgGgggGGgGgggggggg',
      'ggggggggGgggggGGGggggGGggggggggg',
      'ggggggGgGggggggdgggggdggggGggGgg',
      'ggggggGGggggggggggggggggggGGgGgg',
      'gggggggdggggGgggGggggggggggGGggg',
      'gggggggggggggGgGgggggggggggdgggg',
      'gggggggggggggGGGgggggggggggggggg',
      'ggggggggggggggdggggggggggggggggg',
      'ggGggGggggggggggggggggggggggGggg',
      'ggGGgGgGgggggggggGggggggggggGgGg',
      'gggGGggGgGggggggGgggggggggggGGGg',
      'gggdgggGGGggggGgGggggggggggggdgg',
      'ggggggggdgggggGGgggggggggggggggg',
      'gggggggggggggggdgggggggggggggggg',
      'gggggggggggggggggggggGgggggggggg',
      'gggggggggggggggggggggGgGggGgggGg',
      'gggggggggggggggggggggGGGgggGgGgg',
      'ggggggggggggggggggggggdggggGGGgg',
      'ggggggggggggggggGgggggggggggdggg',
      'gggggggggggggggGgggggggggggggggg',
      'gGgggGgggggggGgGgggggggggggggggg',
      'ggGgGggggggggGGggggggggggggggggg',
      'ggGGGgggggggggdggggggggggggggggg',
      'gggdgggggggggggggggggggggggggggg',
      'ggggggggggggggggggggggggGggGgggg',
      'ggggggggggggggggggggggggGGgGgggg',
      'gggggggggggggggggggggggggGGggggg',
      'gggggggggggggggggggggggggdgggggg',
      'gggggggggggggggggggggggggggggggg',
      'gggggggggggggggggggggggggggggggg',
    ],
    'variant-1': [
      'gggggggggggggggggggggggggggggggg',
      'gggggggggggggggggggggggggggggggg',
      'gGgggggggggggggggggggggggggggggg',
      'gGgGggggggggggggggGggGgggggggggg',
      'gGGGggggggggggggggGGgGgggggggggg',
      'ggdggggggggggggggggGGggggggggggg',
      'gggggggggggggggggggdgggggggggGgg',
      'gggggggggGggggggggggggggggggGggg',
      'gggggggggGgGggGgggGgggggggGgGggg',
      'gggggggggGGGgggGgGggggggggGGgggg',
      'ggggggggggdggggGGGggGgggGggdgggg',
      'ggggggggggggggggdggggGgGgggggggg',
      'gggggggggggggggggggggGGGgggggggg',
      'ggggggggGgggggggggggggdggggggggg',
      'gggggggGgggggggggggggggggggggggg',
      'gggggGgGggggGgggGggggggggggggggg',
      'gggggGGggggggGgGgggggggggggggggg',
      'ggggggdggggggGGGgggggggggGggGggg',
      'ggggggggggggggdggggggggggGGgGggg',
      'ggggggggggggggggggggggggggGGgggg',
      'gggggggggggggggggGggggggggdggggg',
      'ggggggggggggggggGggggggggggggggg',
      'gggggGggGgggggGgGggggggggggggggg',
      'gggggGGgGgggggGGgggggggggggggggg',
      'ggggggGGgggggggdggggggggGggGgggg',
      'ggggggdgggggggggggggggggGGgGgggg',
      'gggggggggggggggggggggggggGGggggg',
      'gggggGgggGggggggggGggggggdgggggg',
      'ggggggGgGgggggggggGgGggggggggggg',
      'ggggggGGGgggggggggGGGggggggggggg',
      'gggggggdgggggggggggdgggggggggggg',
      'gggggggggggggggggggggggggggggggg',
    ],
    'variant-2': [
      'gggggggggggggggggggggggggggggggg',
      'gggggggggggggggggggggggggggggggg',
      'gggggggggggggggggggggggggggggggg',
      'gggggggggggggggGgggggggggggggggg',
      'gggggggggggggggGgGgggggggggggggg',
      'ggggggGgggGggggGGGggggggggggggGg',
      'gggggggGgGggggggdggggggggggggGgg',
      'gggggggGGGgggggggggggggggggGgGgg',
      'ggggggggdgggggggggggGggggggGGggg',
      'ggggggggggggggggggggGgGgggggdggg',
      'ggggggggggggggggggggGGGggggggggg',
      'gggggggggggggggggggggdgggggggggg',
      'gggggggggggggggggggggggggggggggg',
      'gggggggggggGgggGggggggggGggGgggg',
      'ggggGgggGgggGgGgggggggggGGgGgggg',
      'gggggGgGggggGGGggggggggggGGggggg',
      'gggggGGGgggggdgggggggggggdgggggg',
      'ggggggdggggggggggggggggggggggggg',
      'gggggggggggggggggggggggggggggggg',
      'ggggggggggggGggggggggggggggggggg',
      'gggggggggggGggggggggggGggggggggg',
      'gggggggggGgGgggggggggGgggggggggg',
      'gggggggggGGggggggggGgGgggggGgggg',
      'ggGgggGgggdggggggggGGggggggGgGgg',
      'gggGgGggggggggggggggdggggggGGGgg',
      'gggGGGggggggggggggggggggggggdggg',
      'ggggdggggggggggggggGggGggggggggg',
      'gggggggggggggGggGggGGgGgggGggGgg',
      'gggggggggggggGGgGgggGGggggGGgGgg',
      'ggggggggggggggGGggggdggggggGGggg',
      'ggggggggggggggdggggggggggggdgggg',
      'gggggggggggggggggggggggggggggggg',
    ],
  },
  faded: {},
  animations: {},
};
